#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

translateicon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAABolJ"
    "REFUWIWlln9sU+Uax7/v+/b09LS2Ox2WbivNOgobXSdwGXCncw1jRETc5r1DcKNCN4ybvzBE"
    "B1Eg5Abnze5ysywWo4lhotOGoBcCSLgout2rGQLKjVznr42rTnTsh8V13bqt3bl/wCln3box"
    "fJImTd7v+30+73POed4HZIaBPVvtSDifMdN98YJihjGrJC0TL9s+lzb0PCu9k6NSrhUVFWXV"
    "1taqZ2R4M5S9vb0WnU63lzH2DRbcJaGx89rv3NxWtO91RKsDXKCU9mk0moampqbUm/GeEqCu"
    "ro43GAy7CSFBABIACQvuvAHQ2CmhqXsIe+Y9JgPIOkJI0GAw7KysrORvCWD//v1Wxti5aOLJ"
    "AN7qDSLj7Vo8+POs69taY/WMsXNerzduNSYFqKqqyqCUdsYYXUhKSno4cV9uCd7oGob4wj50"
    "bLbEVmzevHmFHMeNA6GUXt60aZPzpgB8Pp81Jvmo0Wis9vv9jBBCsP28FS9W2+OdiBBCXC4X"
    "M5lMTxBChpQQPp/POiVAfX09x3Hcp8rn6HQ6V0+VbKpYvnx5HiHkN9mP47jWYDDIxQUQRfE5"
    "5ckdDseaW00uR3Z2dj6AUdnXaDTumBTAZDKZCSEBWSiK4s54pjabrVilUh0C0IrThlb0/ekQ"
    "DP7CeHpRFHcrHkUgNzfXNAFAr9fXKF64L91uNxdrFAwGOUEQ3hz3pnsv3vgqRisPYPtmFrvv"
    "yJEjPGPsK8Xhdo8DWLFiBc8YuyIL7Hb7hpaWlrRYo9mzZz894bNUAjR2SnhGfCp2HyxrUy0W"
    "y8OKA/4vJyeHEXK9FV+9etUViURmAwCltNvj8fyruLh4e2lpaVYgEEiSu6bf7y+atrU+Mj+q"
    "kdYhSXo3PxO9i56v2Tj6IaV0AAAikYgtIyNjMQBQAOjo6HDJm3ieP+H1eu9zOBzvnDhx4vGV"
    "K1cO2O32iuttOzwtgCCMAID0yuoKfLNlABUrH8fS9/7hcbru4TiuWZYdP348JwowMjKSLi9o"
    "tdrzgUBg8eHDh88yxsKU0iWhUCi0cePGxHA4vHBagAsfLJHWXU5Ein0Ef9m2EIwbw7qfzmB7"
    "7mKVSvUfWTY8PJweBZDLDwCU0i7GmMZkMmFwcHCgra1tgcvl+uLUqVN/liTJMC3AYL8BqzwP"
    "4NAjX+DHqkzcbh1E284whoIqrVbbJcuCwWBiFADAmLxACFEDGEtOTg4zxtQ8z4f6+/s1PT09"
    "r9lstocIIZfiJk+aewk7zOtJ1fv7sfdeDeYuDCE0oIK5YQwYQyQSmXD9UwBgjHUrSjMHQPeq"
    "VatEjUZzW2Vl5dkzZ87cDQC1tbWfU0r74wIYTFfR4r5W5j2X7oa77Cy6v78N5SsSkeXqHR0d"
    "nSNLBUEYiAKo1epv5YVQKLQkKyurubm5+R5Jkrry8vJC4XA48+jRo2JnZ2evJEmauADDQQ3+"
    "/Wuv9ECeiIM16dhxMIzlhT/jgyv3Yk3bh6FQKEeWqtXqr+WSE4fDsQY3OlXP0NAQn5CQ4Kuo"
    "qDAbDIZGj8djamho4OQumJ2dnatWq6/deN6LEj6b/wleOZ4nd0O8Xsjjbx+bID3ZiB//a0Z/"
    "qe9+Yb2ZEDIs5ykpKfljtBHl5+frKKXRNux0OgvT09OLzWbzU6dPn570Ltfr9dsYYy8h8tg+"
    "PIptk2lgKUjFo9gGg7/QaDRW40YjutzQ0MDGtWJBEA7IAo7jWgghZNeuXY7JjGcSaN/r6Ovr"
    "S6CU/iL76/X6mui6/Ke8vHwRgIgsSk1NLf29yeXQ6XSvyr6EkIAgCMkTAAghRBCERoXQv2XL"
    "lt9dAavVuhmKu0MUxeeU6+MA3G73LErpD4oX8oetW7fOv9XkNpttAxSzAMdxH5WVlcUfSAgh"
    "pKCgYBlRzAWU0p6bGUxQgzuwes58QghZunSpoNfra5WPlDH2lU6nM03YN5nZsmXLCpQQACSe"
    "5w+53e5FEwzeVXNY07YTTd1D+ivvrU1JSdnMGPtOuZcxdvHYsWOWSVLFH8uLior+EGsEQFKp"
    "VAeimzddWIRPUj6TZwGSmTsaq+d53tfe3p4Qt3LxFgghxOPx6LVa7d+JYroF8BEhhKDs12q8"
    "0TU8bhhZcKfy1N+lpaWVTOU/LYAcJ0+etOp0ur9eH9evAXSst0B8YZ8SgjjzhjmO+2dycnJp"
    "fX39hJHulgHk8Hq9rK6uLm2cwYvVdoTK38TrP0W0KZEZj/AzApjSqEZ9B85/mzatMCb+D0NI"
    "ikG6E+kVAAAAAElFTkSuQmCC")
gettranslateiconData = translateicon.GetData
gettranslateiconImage = translateicon.GetImage
gettranslateiconBitmap = translateicon.GetBitmap
gettranslateiconIcon = translateicon.GetIcon

